apiVersion: v1
kind: Service
metadata:
  name: backend-via
  labels: 
    app: backend-via
spec:
  selector:
    app: backend-via
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
