name: Backend CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure Kubernetes Context
        run: kubectl config use-context minikube

      - name: Apply Backend Manifests
        run: kubectl apply -f k8s/backend-deployment.yaml -f kubernetes/backend-service.yaml
