name: Frontend CD Workflow

on:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Try the cluster!
        run: kubectl get pods -A

      - name: Configure Kubernetes Context
        run: kubectl config use-context minikube

      - name: Apply Frontend Manifests
        run: kubectl apply -f kubernetes/frontend-deployment.yaml -f kubernetes/frontend-service.yaml
        
      - name: Open Minikube Dashboard
        run: minikube dashboard
